### ISSUE TITLE
Unit of work And Repository pattern

### ISSUE THREAD

**Issue by RajasekharwhY** [RajasekharwhY/Build-your-muscle#11]

**Comment by RajaGitHubRepo** [comment]
The Repository and unit of work patterns are intended to create an abstraction layer between Data Access layer and the business logic layer of an application. Implementing these patterns can help insulate your application from changes in the data store and can felicitate unit testing or test-driven development (TDD)

**Comment by RajasekharwhY** [comment]
Unit of work:
---------------
Unit of work is the concept related to the effective implementation of the repository pattern. Unit of work is referred to as a single transaction that involves multiple operations of insert/update/delete ..etc..
(https://www.c-sharpcorner.com/UploadFile/b1df45/unit-of-work-in-repository-pattern/)

**Comment by RajasekharwhY** [comment]
Example implantation will be in other repository.
